create extension if not exists pgcrypto;

create table if not exists public.assets (
  id uuid primary key default gen_random_uuid(),
  product text not null check (product in ('JEUS','WebtoB','Tomcat','PostgreSQL','Nginx')),
  server_name text not null,
  installed_version text not null,
  latest_version text,
  eos_date date,
  risk text not null default 'safe' check (risk in ('critical','warning','safe')),
  open_vulnerabilities integer not null default 0 check (open_vulnerabilities >= 0),
  owner_name text not null,
  next_action_date date,
  action_status text not null default '검토 필요' check (action_status in ('검토 필요','계획 수립','대응 중','완료')),
  lifecycle_source_url text,
  security_source_url text,
  source_checked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.vulnerabilities (
  id uuid primary key default gen_random_uuid(),
  asset_id uuid not null references public.assets(id) on delete cascade,
  cve_id text not null,
  severity text,
  cvss_score numeric(3,1),
  affected_versions text,
  fixed_version text,
  advisory_url text,
  published_at timestamptz,
  status text not null default '미조치' check (status in ('미조치','대응 중','완료','해당 없음')),
  created_at timestamptz not null default now(),
  unique(asset_id, cve_id)
);

create table if not exists public.sync_logs (
  id bigint generated by default as identity primary key,
  source text not null,
  status text not null,
  message text,
  checked_at timestamptz not null default now()
);

alter table public.assets enable row level security;
alter table public.vulnerabilities enable row level security;
alter table public.sync_logs enable row level security;

create policy "authenticated users manage assets" on public.assets
  for all to authenticated using (true) with check (true);
create policy "authenticated users manage vulnerabilities" on public.vulnerabilities
  for all to authenticated using (true) with check (true);
create policy "authenticated users read sync logs" on public.sync_logs
  for select to authenticated using (true);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists assets_set_updated_at on public.assets;
create trigger assets_set_updated_at before update on public.assets
for each row execute function public.set_updated_at();
