create extension if not exists pgcrypto;

create table if not exists public.assets (
  id uuid primary key default gen_random_uuid(),
  product text not null check (product in ('JEUS','WebtoB','Tomcat','PostgreSQL','Nginx')),
  server_name text not null,
  installed_version text not null,
  latest_version text,
  eos_date date,
  risk text not null default 'safe' check (risk in ('critical','warning','safe')),
  open_vulnerabilities integer not null default 0 check (open_vulnerabilities >= 0),
  owner_name text not null,
  next_action_date date,
  action_status text not null default '검토 필요' check (action_status in ('검토 필요','계획 수립','대응 중','완료')),
  lifecycle_source_url text,
  security_source_url text,
  source_checked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.vulnerabilities (
  id uuid primary key default gen_random_uuid(),
  asset_id uuid not null references public.assets(id) on delete cascade,
  cve_id text not null,
  severity text,
  cvss_score numeric(3,1),
  affected_versions text,
  fixed_version text,
  advisory_url text,
  published_at timestamptz,
  status text not null default '미조치' check (status in ('미조치','대응 중','완료','해당 없음')),
  created_at timestamptz not null default now(),
  unique(asset_id, cve_id)
);

create table if not exists public.sync_logs (
  id bigint generated by default as identity primary key,
  source text not null,
  status text not null,
  message text,
  checked_at timestamptz not null default now()
);

create table if not exists public.tracking_targets (
  id uuid primary key default gen_random_uuid(),
  solution_name text not null,
  installed_version text not null,
  target_patch_version text,
  lifecycle_slug text,
  lifecycle_url text,
  security_url text,
  eos_date date,
  latest_version text,
  last_checked_at timestamptz,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(solution_name, installed_version)
);

create table if not exists public.notice_actions (
  id uuid primary key default gen_random_uuid(),
  notice_id text not null unique,
  product text not null,
  version text,
  notice_type text not null check (notice_type in ('보안 패치','EOS')),
  severity text not null default 'info',
  title text not null,
  summary text,
  detail text,
  fixed_version text,
  published_at date,
  source_url text,
  source_name text,
  acknowledged_by uuid not null default auth.uid(),
  acknowledged_email text not null,
  acknowledged_role text not null check (acknowledged_role in ('admin','viewer')),
  acknowledged_at timestamptz not null default now(),
  plan_start_date date,
  plan_end_date date,
  next_action_date date not null,
  action_status text not null default '검토 필요' check (action_status in ('검토 필요','계획 수립','대응 중','완료')),
  updated_at timestamptz not null default now()
);

alter table public.assets enable row level security;
alter table public.vulnerabilities enable row level security;
alter table public.sync_logs enable row level security;
alter table public.tracking_targets enable row level security;
alter table public.notice_actions enable row level security;

create policy "authenticated users read assets" on public.assets
  for select to authenticated using ((auth.jwt() ->> 'email') in ('admin@opswatch.local','viewer@opswatch.local'));
create policy "admin inserts assets" on public.assets
  for insert to authenticated with check ((auth.jwt() ->> 'email') = 'admin@opswatch.local');
create policy "admin updates assets" on public.assets
  for update to authenticated using ((auth.jwt() ->> 'email') = 'admin@opswatch.local') with check ((auth.jwt() ->> 'email') = 'admin@opswatch.local');
create policy "admin deletes assets" on public.assets
  for delete to authenticated using ((auth.jwt() ->> 'email') = 'admin@opswatch.local');
create policy "authenticated users read vulnerabilities" on public.vulnerabilities
  for select to authenticated using ((auth.jwt() ->> 'email') in ('admin@opswatch.local','viewer@opswatch.local'));
create policy "admin manages vulnerabilities" on public.vulnerabilities
  for all to authenticated using ((auth.jwt() ->> 'email') = 'admin@opswatch.local') with check ((auth.jwt() ->> 'email') = 'admin@opswatch.local');
create policy "authenticated users read sync logs" on public.sync_logs
  for select to authenticated using ((auth.jwt() ->> 'email') in ('admin@opswatch.local','viewer@opswatch.local'));
create policy "authenticated users read tracking targets" on public.tracking_targets
  for select to authenticated using ((auth.jwt() ->> 'email') in ('admin@opswatch.local','viewer@opswatch.local'));
create policy "admin inserts tracking targets" on public.tracking_targets
  for insert to authenticated with check ((auth.jwt() ->> 'email') = 'admin@opswatch.local');
create policy "admin updates tracking targets" on public.tracking_targets
  for update to authenticated using ((auth.jwt() ->> 'email') = 'admin@opswatch.local') with check ((auth.jwt() ->> 'email') = 'admin@opswatch.local');
create policy "admin deletes tracking targets" on public.tracking_targets
  for delete to authenticated using ((auth.jwt() ->> 'email') = 'admin@opswatch.local');
create policy "authenticated users read notice actions" on public.notice_actions
  for select to authenticated using ((auth.jwt() ->> 'email') in ('admin@opswatch.local','viewer@opswatch.local'));
create policy "authenticated users acknowledge notices" on public.notice_actions
  for insert to authenticated with check (
    acknowledged_by = auth.uid()
    and acknowledged_email = (auth.jwt() ->> 'email')
    and (auth.jwt() ->> 'email') in ('admin@opswatch.local','viewer@opswatch.local')
  );
create policy "admin updates notice actions" on public.notice_actions
  for update to authenticated using ((auth.jwt() ->> 'email') = 'admin@opswatch.local') with check ((auth.jwt() ->> 'email') = 'admin@opswatch.local');

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists assets_set_updated_at on public.assets;
create trigger assets_set_updated_at before update on public.assets
for each row execute function public.set_updated_at();

drop trigger if exists tracking_targets_set_updated_at on public.tracking_targets;
create trigger tracking_targets_set_updated_at before update on public.tracking_targets
for each row execute function public.set_updated_at();

drop trigger if exists notice_actions_set_updated_at on public.notice_actions;
create trigger notice_actions_set_updated_at before update on public.notice_actions
for each row execute function public.set_updated_at();
